testcontainers/community-module-registry

- modules/opensearch.md
Add OpenSearch Testcontainers community module
> Add OpenSearch Testcontainers community module

- README.md
Just a small contributor documentation PR
> Extend the format notes based on the WireMock module experiences

- modules/wiremock.md
Added entry for nodejs testcontainers module for wiremock
[See more](https://github.com/wiremock/wiremock-testcontainers-node/issues/4)
@oleg-nenashev
> Added entry for nodejs testcontainers module for wiremock

- modules/microcks.md
> feat: add microcks Go module

- modules/dynamodb.md
Add [DynamoDB Local](https://docs.aws.amazon.com/amazondynamodb/latest/developerguide/DynamoDBLocal.html) module for Testcontainers Go
> Add DynamoDB Go module

- modules/dynamodb.md
- modules/surrealdb.md
It adds the Go module for SurrealDB, fixing some indents in code snippets.
> feat: add surrealdb Go module

- modules/qdrant/index.md
Also, mark java module as a official module.
> Add Qdrant as a official partner

- modules/influxdb/index.md
It adds the influxdb Go module (see https://github.com/testcontainers/testcontainers-go/pull/1703)
> feat: add influxdb go module

- modules/dapr/index.md
Keeping Dapr updated to latest stable version
> Upgrading Dapr version to 1.13.2

- modules/mssql/index.md
related to https://github.com/testcontainers/testcontainers-dotnet/issues/1189
> docs: mssql align dotnet image with go tag

- modules/ollama/index.md
The docs link should be fixed first.
> [ollama] Add nodejs section

- modules/grafana/index.md
Adds Grafana LGTM module to Go catalog
> chore: add grafana lgtm Go module

- modules/databend/index.md
Ref: https://github.com/testcontainers/testcontainers-rs-modules-community/pull/207
> feat: add databend rust testcontainer docs

- modules/etcd/index.md
- modules/yugabytedb/index.md
- **feat: include etcd Go module**
- **feat: include yugabyteDB Go module**
> feat: add yugabytedb and etcd Go modules

- README.md
> Update README.md snippets to be formatted as yaml

- modules/azurite/index.md
Dependent on release of https://github.com/testcontainers/testcontainers-node/commit/90c537d4054ccda9f69ecf9bbd4e615a2c2e668b
> Add Azurite for Node.js

- modules/k3s/index.md
> Add K3s for Node.js

- modules/microcks/index.md
> feat: add microcks Dotnet module

- modules/minio/index.md
Add MinIO for Node.js. Pending release of [this commit](https://github.com/testcontainers/testcontainers-node/commit/0e536e9913681eac314477948b871d3846010980) in testcontainer-node repo.
> Add MinIO for Node.js

- modules/weaviate/index.md
We recently received a Weaviate module contribution for .NET. The pull request adds the .NET module to the catalog, and it will be available in the next release, `4.2.0`.
> Add Weaviate for .NET

- modules/dapr/index.md
Thanks @eddumelendez for all the help on this !
> Updating Dapr artifacts that are now in Dapr Upstream!

- modules/cosmodb/index.md
- modules/eventstoredb/index.md
Added some missing nodejs modules
> Add node section to EventStoreDb

- modules/arangodb/index.md
- modules/google-cloud/index.md
- **chore: update GCloud Go code**
- **feat: add arangodb go**
> chore: update Go modules

- modules/qdrant/index.md
Do not merge until module is released.
> Add dotnet section to qdrant

- modules/vault/index.md
> Add nodejs vault module

- modules/couchdb/index.md
- modules/etcd/index.md
- modules/vault/index.md
> Add node modules
